# Copyright (c) 2026 Simon Peter
#
# SPDX-License-Identifier: BSD-2-Clause

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = TheLounge Nosterm Quassel

include $(GNUSTEP_MAKEFILES)/aggregate.make
